const nodeNameTranslations: Record<string, string> = {
  'Strength': '力量',
  'Dexterity': '敏捷',
  'Intelligence': '智慧',
  'Life': '生命',
  'Mana': '魔力',
  'Energy Shield': '能量護盾',
  'Armour': '護甲',
  'Evasion': '閃避',
  'Block': '格擋',
  'Accuracy': '命中',
  'Attack Speed': '攻擊速度',
  'Cast Speed': '施放速度',
  'Spell Damage': '法術傷害',
  'Fire Damage': '火焰傷害',
  'Cold Damage': '冰冷傷害',
  'Lightning Damage': '閃電傷害',
  'Chaos Damage': '混沌傷害',
  'Physical Damage': '物理傷害',
  'Elemental Damage': '元素傷害',
  'Projectile Damage': '投射物傷害',
  'Melee Damage': '近戰傷害',
  'Attack Damage': '攻擊傷害',
  'Physical Attack Damage': '物理攻擊傷害',
  'Minion Damage': '召喚物傷害',
  'Minion Life': '召喚物生命',
  'Life Regeneration': '生命回復',
  'Life Leech': '生命偷取',
  'Mana Regeneration': '魔力回復',
  'Reservation Efficiency': '保留效用',
  'Aura Effect': '光環效果',
  'Aura Area of Effect': '光環範圍效果',
  'Area of Effect': '範圍效果',
  'Critical Strike Chance': '暴擊率',
  'Spell Critical Strike Chance': '法術暴擊率',
  'Curse Effect': '詛咒效果',
  'Saboteur': '破壞者',
  'Slayer': '處刑者',
  'Trickster': '詐欺師',
  'Juggernaut': '勇士',
  'Necromancer': '死靈師',
  'Occultist': '秘術家',
  'Pathfinder': '追獵者',
  'Warden': '看守者',
  'Deadeye': '銳眼',
  'Gladiator': '衛士',
  'Guardian': '守護者',
  'Hierophant': '聖宗',
  'Inquisitor': '判官',
  'Elementalist': '元素使',
  'Berserker': '暴徒',
  'Chieftain': '酋長',
  'Champion': '冠軍',
  'Assassin': '刺客',
  'Ward': '保護',
  'Sanctuary': '聖所',
  'Crave the Slaughter': '屠戮之慾',
  'Aspect of Carnage': '血肉之章',
  'War Bringer': '戰爭使者',
  'Rite of Ruin': '毀滅儀式',
  'Defy Pain': '抵禦苦痛',
  'Aul Bloodline': '奧爾血裔',
  'Catarina Bloodline': '卡塔莉娜血裔',
  'Farrul Bloodline': '費爾羅血裔',
  'Farric Will': '費爾羅之志',
  'Fertile Will': '豐富之志',
  'Wild Will': '狂野之志',
  'Huntleader': '狩獵領袖',
  'The King\'s Contempt': '王之蔑視',
  'The King\'s Heritage': '王之傳承',
  'The King\'s Might': '王之威能',
  'Legacy of the King': '王之遺產',
  'Ancestral Fury': '先祖之怒',
  'Death Offering': '死亡奉獻',
  'Untiring': '不懈',
  'Unstoppable': '勢不可擋',
  'Unbreakable': '堅不可破',
  'Undeniable': '不可置疑',
  'Unflinching': '永不動搖',
  'Unrelenting': '殺無赦',
  'Unyielding': '屹立不搖',
  'Harmony of Purpose': '和諧之源',
  'Unwavering Faith': '不動信念',
  'Radiant Crusade': '光輝遠征',
  'Unwavering Crusade': '堅定聖戰',
  'Time of Need': '緊急時刻',
  'Radiant Faith': '信念之輝',
  'Bastion of Hope': '希望壁壘',
  'Sanctuary of Thought': '意識聖殿',
  'Ritual of Awakening': '昇華儀式',
  'Conviction of Power': '力量定罪',
  'Illuminated Devotion': '無上奉獻',
  'Arcane Blessing': '秘能庇護',
  'Sign of Purpose': '標記之印',
  'Divine Guidance': '神聖指引',
  'Pursuit of Faith': '信念之訴',
  'Pious Path': '廉簡之途',
  'Instruments of Zeal': '狂熱儀',
  'Instruments of Virtue': '美德儀',
  'Righteous Providence': '正義之庭',
  'Inevitable Judgement': '命運審判',
  'Augury of Penitence': '懺悔之卜',
  'Tasalio, Cleansing Water': '淨化之水．塔薩里奧',
  'Sanguimancy': '占血術',
  'Cannibalised Faith': '食人族信仰',
  'Crimson Power': '緋紅之力',
  'Corruption\'s Embrace': '腐化之擁',
  'Lycia Bloodline': '利希亞血裔',
  'Bitter Heresy': '苦澀異端',
  'Sinner Saint': '罪人聖徒',
  'Farewell to Flesh': '告別血肉',
  'Blood Hunt': '鮮血獵捕',
  'Warlock of the Mists': '嵐之術士',
  'Soul Splitting': '靈魂撕裂',
  'Creeping Lobotomy': '前額葉切除術',
  'Black Mass': '黑暗彌撒',
  'Foul Pact': '邪惡契約',
  'Choir of the Damned': '惡魔樂團',
  'Oshabi Bloodline': '奧莎比血裔',
  'The Primal Owl': '原始貓頭鷹',
  'The Wild Bear': '荒野之熊',
  'The Vivid Cat': '鮮活之貓',
  'Elusive effect': '朦朧效應',
  'Seal gain frequency': '封印獲取頻率',
  'Umbral Army': '幽影軍團',
  'Prolonged Servitude': '無期奴役',
  'Nameless Bloodline': '無名血裔',
  'The Unseen Hand': '未見之手',
  'Toad\'s Price': '蟾蜍的代價',
  'Serpent\'s Price': '腹蛇的代價',
  'Beetle\'s Price': '甲蟲的代價',
  'Unlight Silhouette': '無光輪廓',
  'Olroth Bloodline': '奧爾羅斯血裔',
  'Enhanced Starlight': '增幅星光',
  'Volatile Runes': '易爆符文',
  'Boon of the River': '河之祝福',
  'Boon of the Mountain': '山之祝福',
  'Boon of the Sun': '日之祝福',
  'Wildwood Primalist': '荒野始者',
  'Warden of the Maji': '聖賢守護者',
  'Wildwood Blessing': '荒林祝福',
  'Oath of the Maji': '聖賢之誓',
  'Ascendant': '昇華使徒',
  'Templar Ascendancy': '聖騎士昇華職業',
  'Marauder Ascendancy': '野蠻人昇華職業',
  'Witch Ascendancy': '女巫昇華職業',
  'Duelist Ascendancy': '決鬥者昇華職業',
  'Ranger Ascendancy': '遊俠昇華職業',
  'Shadow Ascendancy': '暗影刺客昇華職業',
  'Path of the Templar': '聖騎士之道',
  'Path of the Marauder': '野蠻人之道',
  'Path of the Duelist': '決鬥者之道',
  'Path of the Witch': '女巫之道',
  'Path of the Shadow': '暗影刺客之道',
  'Path of the Ranger': '遊俠之道',
  'Burning Damage Multiplier with Attacks': '攻擊的燃燒傷害加成',
  'Brand Range and Brand Recall Cooldown Recovery': '烙印範圍和烙印呼喚冷卻恢復率',
  'Increased Energy Shield Leeched': '增加能量護盾偷取',
  'Damage if Consumed a Corpse': '消耗屍體後的傷害',
  'Bleed and Critical Strike Chance': '流血機率和暴擊率',
  'Aggravate Bleeding On Critical Strike Chance': '暴擊時惡化流血機率',
  'Physical Damage, Life Leeched per Second': '物理傷害、每秒生命偷取',
  'Armour and Energy Shield, Shrine Buff Effect': '護甲和能量護盾、神龕增益效果',
  'Chaos Bloodline': '混沌血裔',
  'Vaal Souls': '瓦爾靈魂',
  'Gore Dancer': '血腥舞者',
  'Farrul\'s Will': '費爾羅之志',
  'Tukohama, War\'s Herald': 'Tukohama, War\'s Herald',
  'Ramako, Sun\'s Light': 'Ramako, Sun\'s Light',
  'Valako, Storm\'s Embrace': 'Valako, Storm\'s Embrace',
  'Sione, Sun\'s Roar': 'Sione, Sun\'s Roar',
  'Ngamahu, Flame\'s Advance': 'Ngamahu, Flame\'s Advance',
  'Hinekora, Death\'s Fury': 'Hinekora, Death\'s Fury',
  'Divine Shield': '聖盾',
  'Resolute Technique': '堅毅之心',
  'Spiritual Aid': '精神救助',
  'Divine Judgement': '聖之審判',
  'Divine Wrath': '聖之雷霆',
  'Blade Master': '刀劍宗師',
  'Crusader': '十字軍',
  'Tenacity': '不屈不撓',
  'Persistence': '堅持不懈',
  'Righteous Army': '正義軍團',
  'Redemption': '救贖',
  'Smashing Strikes': '沉重之擊',
  'Cleaving': '劈砍',
  'Slaughter': '屠殺',
  'Charm Socket': '咒符插槽',
  'Attack Mana Cost': '攻擊魔力消耗',
  'Attack and Cast Speed': '攻擊和施放速度',
  'Armour and Energy Shield': '護甲和能量護盾',
  'Armour and Evasion': '護甲和閃避',
  'Life and Armour': '生命和護甲',
  'Life and Energy Shield': '生命和能量護盾',
  'Evasion and Energy Shield': '閃避和能量護盾',
  'Elemental Damage and Resistances': '元素傷害和抗性',
  'Elemental Damage, Attack and Cast Speed': '元素傷害、攻擊與施放速度',
  'Minion Damage and Life': '召喚物傷害和生命',
  'Mana and Mana Regeneration': '魔力和魔力回復',
  'Mana Regeneration, Totem Placement Speed': '魔力回復速度、圖騰放置速度',
  'Mana Regeneration, Arcane Surge Effect': '魔力回復速度、秘能波動效果',
  'Position Proxy': '位置代理',
  'Passive Point': '天賦點',
  'Basic Jewel Socket': '基礎珠寶插槽',
  'Small Jewel Socket': '小型珠寶插槽',
  'Medium Jewel Socket': '中型珠寶插槽',
  'Large Jewel Socket': '大型珠寶插槽',
  'Attack Mastery': '攻擊專精',
  'Life Mastery': '生命專精',
  'Mana Mastery': '魔力專精',
  'Fire Mastery': '火焰專精',
  'Cold Mastery': '冰冷專精',
  'Lightning Mastery': '閃電專精',
  'Elemental Mastery': '元素專精',
  'Physical Mastery': '物理專精',
  'Critical Mastery': '暴擊專精',
  'Caster Mastery': '法術專精',
  'Bow Mastery': '弓專精',
  'Axe Mastery': '斧專精',
  'Claw Mastery': '爪專精',
  'Dagger Mastery': '匕首專精',
  'Sword Mastery': '劍專精',
  'Mace Mastery': '錘專精',
  'Staff Mastery': '長杖專精',
  'Shield Mastery': '盾牌專精',
  'Totem Mastery': '圖騰專精',
  'Trap Mastery': '陷阱專精',
  'Mark Mastery': '印記專精',
  'Poison Mastery': '中毒專精',
  'Charge Mastery': '充能專精',
  'Brand Mastery': '烙印專精',
  'Link Mastery': '連結專精',
  'Stun Mastery': '暈眩專精',
  'Retaliation Mastery': '復仇專精',
  'Dual Wielding Mastery': '雙持專精',
  'Curse Mastery': '詛咒專精',
  'Warcry Mastery': '戰吼專精',
  'Banner Mastery': '鬥旗專精',
  'Mine Mastery': '地雷專精',
  'Flask Mastery': '藥劑專精',
  'Fortify Mastery': '護體專精',
  'Reservation Mastery': '保留專精',
  'Armour Mastery': '護甲專精',
  'Evasion Mastery': '閃避專精',
  'Energy Shield Mastery': '能量護盾專精',
  'Leech Mastery': '偷取專精',
  'Bleeding Mastery': '流血專精',
  'Impale Mastery': '穿刺專精',
  'Recovery Mastery': '恢復專精',
  'Protection Mastery': '保護專精',
  'Tincture Mastery': '萃取物專精',
  'Tincture Effect': '萃取物效果',
  'Slower Mana Burn': '較慢魔力灼燒',
  'Slower Rage Decay': '較慢盛怒衰減',
  'Rage on Hit': '擊中獲得盛怒',
  'Damage Over Time Mastery': '持續傷害專精',
  'Minion Offence Mastery': '召喚物侵略專精',
  'Minion Defence Mastery': '召喚物防禦專精',
  'Block Mastery': '格擋專精',
  'Warcry Buff Effect': '戰吼增益效果',
  'Warcry Duration': '戰吼持續時間',
  'Banner Valour Gained': '戰旗英勇值獲得',
  'Spell Suppression': '法術壓抑',
  'Trap Damage': '陷阱傷害',
  'Skill Duration': '技能持續時間',
  'Damage Over Time Multiplier': '持續傷害加成',
  'Energy Shield Leech': '能量護盾偷取',
  'Elemental Resistances': '元素抗性',
  'Movement Speed': '移動速度',
  'Energy Shield Recharge Rate': '能量護盾充能率',
  'Impale Effect': '穿刺效果',
  'Retaliation Skill Damage': '復仇技能傷害',
  'Two Handed Melee Damage': '雙手近戰傷害',
  'Two Hand Mastery': '雙手專精',
  'Attributes Mastery': '屬性專精',
  'Mine Damage': '地雷傷害',
  'Melee Damage and Strike Range': '近戰傷害和打擊距離',
  'Curse Mana Reservation Efficiency': '詛咒魔力保留效用',
  'Curse Duration': '詛咒持續時間',
  'Curse Cast Speed': '詛咒施放速度',
  'Chill Effect': '冰緩效果',
  'Weapon Fire Damage': '武器火焰傷害',
  'Warcry Speed': '戰吼速度',
  'Stun Threshold Reduction': '敵人暈眩門檻降低',
  'Stance Skill Cooldown Recovery': '姿態技能冷卻恢復率',
  'Spell Critical Strike Multiplier': '法術暴擊加成',
  'Power Charge Duration': '暴擊球持續時間',
  'Maximum Fortification': '最大護體',
  'Mana and Reduced Mana Cost': '魔力和減少魔力消耗',
  'Mana Regeneration, Mana': '魔力回復速度、魔力',
  'Mana Regeneration and Life': '魔力回復和生命',
  'Life Gain on Hit': '擊中獲得生命',
  'Life Leech Speed': '生命偷取速度',
  'Frenzy Charge Duration': '狂怒球持續時間',
  'Freeze Chance': '冰凍機率',
  'Flask Charges Gained': '藥劑充能獲得量',
  'Fire Resistance': '火焰抗性',
  'Cold Resistance': '冰冷抗性',
  'Lightning Resistance': '閃電抗性',
  'Banner Duration': '鬥旗持續時間',
  'Attack Damage with Shield': '持盾時攻擊傷害',
  'Retaliation Skill Cooldown Recovery': '復仇技能冷卻恢復率',
  'Warcry Cooldown Recovery': '戰吼冷卻恢復率',
  'Endurance Charge Duration': '耐力球持續時間',
  'Flask Effect and Charges Gained': '藥劑效果和充能獲得量',
  'Attack Speed, Block Chance': '攻擊速度、格擋率',
  'Reservation Efficiency of Heralds': '捷的保留效用',
  'Projectile Damage and Accuracy': '投射物傷害、命中率',
  'Spell Area of Effect': '法術範圍效果',
  'Spell Damage Over Time Multiplier': '法術持續傷害加成',
  'Spell Damage Over Time': '法術持續傷害',
  'Movement Speed and Spell Suppression': '移動速度和法術壓抑',
  'Mana Flasks': '魔力藥劑',
  'Life Flasks and Flask Duration': '生命藥劑和藥劑持續時間',
  'Herald Buff Effect': '捷增益效果',
  'Energy Shield and Energy Shield Recharge Rate': '能量護盾和能量護盾充能率',
  'Evasion and Blind Effect': '閃避和致盲效果',
  'Dual Wield Spell Damage and Movement Speed': '雙持法術傷害和移動速度',
  'Damage Over Time': '持續傷害',
  'Evil Eye': '邪眼',
  'Armour and Elemental Resistances': '護甲和元素抗性',
  'Armour and Life': '護甲和生命',
  'Armour and Life Regeneration': '護甲和生命回復',
  'Armour, Attack Speed': '護甲、攻擊速度',
  'Armour, Chaos Resistance': '護甲、混沌抗性',
  'Armour, Movement Speed': '護甲、移動速度',
  'Axe Damage': '斧傷害',
  'Axe Damage and Attack Speed': '斧傷害和攻擊速度',
  'Bleed Chance': '流血機率',
  'Bow Damage': '弓傷害',
  'Chaos Damage Over Time Multiplier': '混沌持續傷害加成',
  'Evasion and Life': '閃避和生命',
  'Evasion and Spell Suppression': '閃避和法術壓抑',
  'Minion Attack and Cast Speed': '召喚物攻擊和施放速度',
  'Physical and Chaos Damage': '物理和混沌傷害',
  'Primal Wisps found': '發現的原始微光',
  'Rage Mastery': '盛怒專精',
  'Staff Block': '長杖格擋',
  'Wand Damage': '法杖傷害',
  'Weapon Elemental Damage': '武器元素傷害',
  'Wild Wisps found': '發現的狂野微光',
  'Vivid Wisps found': '發現的鮮明微光'
};

const termTranslations: Array<[string, string]> = [
  ['Chance to Block Attack Damage while Dual Wielding or holding a Shield', '雙持或持盾時的攻擊傷害格擋率'],
  ['Chance to Block Attack Damage while holding a Shield', '持盾時的攻擊傷害格擋率'],
  ['Chance to Block Attack Damage while Dual Wielding', '雙持時的攻擊傷害格擋率'],
  ['Chance to Block Spell Damage while wielding a Staff', '持長杖時的法術傷害格擋率'],
  ['Chance to Block Attack Damage while wielding a Staff', '持長杖時的攻擊傷害格擋率'],
  ['Mana Reservation Efficiency of Skills', '技能魔力保留效用'],
  ['Chance to Block Attack Damage', '攻擊傷害格擋率'],
  ['Chance to Block Spell Damage', '法術傷害格擋率'],
  ['Chance to Suppress Spell Damage', '壓抑法術傷害率'],
  ['Critical Strike Multiplier', '暴擊加成'],
  ['Critical Strike Chance', '暴擊率'],
  ['Spell Critical Strike Chance', '法術暴擊率'],
  ['Damage Over Time Multiplier', '持續傷害加成'],
  ['Damage Over Time with Bow Skills', '弓技能持續傷害'],
  ['Damage with Ailments', '異常狀態傷害'],
  ['effect of Non-Curse Auras from your Skills', '來自你的技能的非詛咒光環效果'],
  ['Area of Effect of Aura Skills', '光環技能範圍效果'],
  ['maximum Energy Shield', '最大能量護盾'],
  ['Energy Shield', '能量護盾'],
  ['maximum Mana', '最大魔力'],
  ['maximum Life', '最大生命'],
  ['maximum Elemental Resistances', '最大元素抗性'],
  ['Mana Regeneration Rate', '魔力回復速度'],
  ['Life Regeneration Rate', '生命回復速度'],
  ['Energy Shield Recharge Rate', '能量護盾充能率'],
  ['Global Accuracy Rating', '全域命中值'],
  ['Accuracy Rating', '命中值'],
  ['Evasion Rating', '閃避值'],
  ['Attack Speed', '攻擊速度'],
  ['Cast Speed', '施放速度'],
  ['Skill Effect Duration', '技能效果持續時間'],
  ['Spell Damage', '法術傷害'],
  ['Projectile Damage', '投射物傷害'],
  ['Melee Physical Damage', '近戰物理傷害'],
  ['Physical Damage', '物理傷害'],
  ['Fire Damage', '火焰傷害'],
  ['Cold Damage', '冰冷傷害'],
  ['Lightning Damage', '閃電傷害'],
  ['Chaos Damage', '混沌傷害'],
  ['Elemental Damage', '元素傷害'],
  ['Area of Effect', '範圍效果'],
  ['Area Damage', '範圍傷害'],
  ['Aura Skills', '光環技能'],
  ['Non-Curse Auras', '非詛咒光環'],
  ['your Curses', '你的詛咒'],
  ['Curse Duration', '詛咒持續時間'],
  ['Curse Effect', '詛咒效果'],
  ['Flask Charges gained', '藥劑充能獲得量'],
  ['Flask Effect Duration', '藥劑效果持續時間'],
  ['Flasks applied to you have', '施加於你的藥劑有'],
  ['Movement Speed', '移動速度'],
  ['Minions', '召喚物'],
  ['Armour', '護甲'],
  ['Life Leech', '生命偷取'],
  ['Mana Leech', '魔力偷取'],
  ['Life Recovery from Flasks', '來自藥劑的生命回復'],
  ['total Recovery per second from Life Leech', '每秒生命偷取總回復'],
  ['Enemy Stun Threshold', '敵人暈眩門檻'],
  ['Totem Placement speed', '圖騰放置速度'],
  ['Warcry Buff Effect', '戰吼增益效果'],
  ['Warcry Duration', '戰吼持續時間'],
  ['Valour gained', '獲得的英勇值'],
  ['Quantity of Wild Wisps found in the Viridian Wildwood', '在碧綠林野中發現的狂野微光數量'],
  ['Quantity of Vivid Wisps found in the Viridian Wildwood', '在碧綠林野中發現的鮮明微光數量'],
  ['Quantity of Primal Wisps found in the Viridian Wildwood', '在碧綠林野中發現的原始微光數量'],
  ['Two Handed Melee Weapons', '雙手近戰武器'],
  ['holding a Shield', '持盾'],
  ['Dual Wielding', '雙持'],
  ['Attacks', '攻擊'],
  ['Attack', '攻擊'],
  ['Leeched as Life', '偷取生命'],
  ['Leeched as Mana', '偷取魔力'],
  ['with Bows', '使用弓時'],
  ['with Wands', '使用法杖時'],
  ['with Swords', '使用劍時'],
  ['with Axes', '使用斧時'],
  ['with Maces or Sceptres', '使用錘或權杖時'],
  ['with Two Handed Melee Weapons', '使用雙手近戰武器時'],
  ['while holding a Shield', '持盾時'],
  ['while Dual Wielding', '雙持時'],
  ['while wielding a Staff', '持長杖時'],
  ['per Frenzy Charge', '每個狂怒球'],
  ['per Endurance Charge', '每個耐力球'],
  ['per Power Charge', '每個暴擊球'],
  ['Wild Wisps found', '發現的狂野微光'],
  ['Vivid Wisps found', '發現的鮮明微光'],
  ['Primal Wisps found', '發現的原始微光'],
  ['Valour gained', '獲得的英勇值'],
  ['Tinctures applied to you', '施加於你的萃取物'],
  ['Mana Burn rate', '魔力灼燒速度'],
  ['Rage', '盛怒'],
  ['Bleeding', '流血'],
  ['Ignite', '點燃'],
  ['Shock', '感電'],
  ['Freeze', '冰凍'],
  ['Blind', '致盲'],
  ['Fortified', '護體'],
  ['Block Recovery', '格擋恢復'],
  ['Stun Duration', '暈眩持續時間'],
  ['Bleed Chance', '流血機率'],
  ['Life', '生命'],
  ['Mana', '魔力'],
  ['Strength', '力量'],
  ['Dexterity', '敏捷'],
  ['Intelligence', '智慧']
];

const sortedTermTranslations = [...termTranslations].sort((a, b) => b[0].length - a[0].length);

const replaceTerms = (text: string): string => {
  let output = text;
  sortedTermTranslations.forEach(([source, target]) => {
    output = output.replaceAll(source, target);
  });
  return output;
};

const regexTransforms: Array<[RegExp, (...groups: string[]) => string]> = [
  [/^\+(\d+) to (.+)$/i, (value, stat) => `+# ${replaceTerms(stat)}`.replace('#', value)],
  [/^\+(\d+(?:\.\d+)?)% chance to (.+)$/i, (value, effect) => `+${value}% ${replaceTerms(effect)}`],
  [/^(\d+(?:\.\d+)?)% increased (.+)$/i, (value, stat) => `增加 ${value}% ${replaceTerms(stat)}`],
  [/^(\d+(?:\.\d+)?)% reduced (.+)$/i, (value, stat) => `降低 ${value}% ${replaceTerms(stat)}`],
  [/^(\d+(?:\.\d+)?)% chance to (.+)$/i, (value, effect) => `${value}% 機率${replaceTerms(effect)}`],
  [/^\+(\d+(?:\.\d+)?)% to ([A-Za-z ]+) Resistance$/i, (value, element) => `+${value}% ${replaceTerms(element)}抗性`],
  [/^\+(\d+(?:\.\d+)?)% to ([A-Za-z ]+) Resistances$/i, (value, element) => `+${value}% ${replaceTerms(element)}抗性`],
  [/^\+(\d+(?:\.\d+)?)% to all Elemental Resistances$/i, (value) => `+#% 全元素抗性`.replace('#', value)],
  [/^\+(\d+(?:\.\d+)?)% to all maximum Elemental Resistances$/i, (value) => `+#% 全部最大元素抗性`.replace('#', value)],
  [/^\+(\d+(?:\.\d+)?)% to Critical Strike Multiplier$/i, (value) => `+${value}% 暴擊加成`],
  [/^(\d+(?:\.\d+)?)% of Attack Damage Leeched as Life$/i, (value) => `${value}% 攻擊傷害偷取生命`],
  [/^(\d+(?:\.\d+)?)% of Spell Damage Leeched as Energy Shield$/i, (value) => `${value}% 法術傷害偷取能量護盾`],
  [/^(\d+(?:\.\d+)?)% increased effect of Non-Curse Auras from your Skills$/i, (value) => `增加 ${value}% 你技能的非詛咒光環效果`],
  [/^(\d+(?:\.\d+)?)% increased Quantity of (.+) found in the Viridian Wildwood$/i, (value, wisp) => `增加 ${value}% 在碧綠林野中發現的${replaceTerms(wisp)}`],
  [/^Attacks have (\d+(?:\.\d+)?)% chance to (.+)$/i, (value, effect) => `攻擊有 ${value}% 機率${replaceTerms(effect)}`],
  [/^Attacks with (.+) deal (\d+(?:\.\d+)?)% increased Damage with Ailments$/i, (weapon, value) => `使用${replaceTerms(weapon)}的攻擊造成 ${value}% 增加異常狀態傷害`],
  [/^(.+) Attacks deal (\d+(?:\.\d+)?)% increased Damage with Ailments$/i, (weapon, value) => `${replaceTerms(weapon)}攻擊造成 ${value}% 增加異常狀態傷害`],
  [/^(.+) Attacks deal (\d+(?:\.\d+)?)% increased Damage with Hits and Ailments$/i, (weapon, value) => `${replaceTerms(weapon)}攻擊造成 ${value}% 增加擊中與異常狀態傷害`],
  [/^Flasks applied to you have (\d+(?:\.\d+)?)% increased Effect$/i, (value) => `施加於你的藥劑增加 ${value}% 效果`],
  [/^Tinctures applied to you have (\d+(?:\.\d+)?)% increased Effect$/i, (value) => `施加於你的萃取物增加 ${value}% 效果`],
  [/^Tinctures applied to you have (\d+(?:\.\d+)?)% reduced Mana Burn rate$/i, (value) => `施加於你的萃取物降低 ${value}% 魔力灼燒速度`],
  [/^Regenerate (\d+(?:\.\d+)?)% of Mana per second$/i, (value) => `每秒回復 ${value}% 魔力`],
  [/^Regenerate (\d+(?:\.\d+)?)% of Life per second$/i, (value) => `每秒回復 ${value}% 生命`],
  [/^Grants (\d+) Passive Skill Point(?:s)?$/i, (value) => `給予 ${value} 點天賦點`],
  [/^Minions deal (\d+(?:\.\d+)?)% increased Damage$/i, (value) => `召喚物造成 ${value}% 增加傷害`],
  [/^Minions have (\d+(?:\.\d+)?)% increased maximum Life$/i, (value) => `召喚物有 ${value}% 增加最大生命`],
  [/^Minions have (\d+(?:\.\d+)?)% increased Attack Speed$/i, (value) => `召喚物有 ${value}% 增加攻擊速度`],
  [/^Minions have (\d+(?:\.\d+)?)% increased Cast Speed$/i, (value) => `召喚物有 ${value}% 增加施放速度`],
  [/^\+(\d+(?:\.\d+)?)% Chance to Block Attack Damage while (.+)$/i, (value, condition) => `+${value}% ${replaceTerms(`Chance to Block Attack Damage while ${condition}`)}`],
  [/^\+(\d+(?:\.\d+)?)% Chance to Block Spell Damage while (.+)$/i, (value, condition) => `+${value}% ${replaceTerms(`Chance to Block Spell Damage while ${condition}`)}`],
  [/^(\d+(?:\.\d+)?)% increased Damage with Bows$/i, (value) => `增加 ${value}% 使用弓時的傷害`],
  [/^(\d+(?:\.\d+)?)% increased Elemental Damage with Attack Skills$/i, (value) => `增加 ${value}% 攻擊技能的元素傷害`],
  [/^(\d+(?:\.\d+)?)% increased Damage Over Time with Bow Skills$/i, (value) => `增加 ${value}% 弓技能持續傷害`],
  [/^(\d+(?:\.\d+)?)% increased Physical Damage with (.+)$/i, (value, weapon) => `增加 ${value}% 使用${replaceTerms(weapon)}時的物理傷害`],
  [/^(\d+(?:\.\d+)?)% increased Damage while wielding a Wand$/i, (value) => `增加 ${value}% 持法杖時的傷害`],
  [/^(\d+(?:\.\d+)?)% increased Attack Speed with Wands$/i, (value) => `增加 ${value}% 使用法杖時的攻擊速度`],
  [/^(\d+(?:\.\d+)?)% increased Accuracy Rating with Wands$/i, (value) => `增加 ${value}% 使用法杖時的命中值`],
  [/^(\d+(?:\.\d+)?)% increased Life Recovery from Flasks$/i, (value) => `增加 ${value}% 來自藥劑的生命回復`],
  [/^(\d+(?:\.\d+)?)% increased Flask Charges gained$/i, (value) => `增加 ${value}% 藥劑充能獲得量`],
  [/^(\d+(?:\.\d+)?)% increased Flask Effect Duration$/i, (value) => `增加 ${value}% 藥劑效果持續時間`],
  [/^(\d+(?:\.\d+)?)% increased total Recovery per second from Life Leech$/i, (value) => `增加 ${value}% 每秒生命偷取總回復`],
  [/^(\d+(?:\.\d+)?)% increased effect of Non-Curse Auras from your Skills$/i, (value) => `增加 ${value}% 你技能的非詛咒光環效果`],
  [/^(\d+(?:\.\d+)?)% increased Area of Effect of Aura Skills$/i, (value) => `增加 ${value}% 光環技能範圍效果`],
  [/^(\d+(?:\.\d+)?)% increased Effect of (.+)$/i, (value, effect) => `增加 ${value}% ${replaceTerms(effect)}效果`],
  [/^(\d+(?:\.\d+)?)% increased Valour gained$/i, (value) => `增加 ${value}% 獲得的英勇值`],
  [/^(\d+(?:\.\d+)?)% reduced Enemy Stun Threshold$/i, (value) => `降低 ${value}% 敵人暈眩門檻`],
  [/^(\d+(?:\.\d+)?)% chance to Impale Enemies on Hit with Attacks$/i, (value) => `攻擊擊中時有 ${value}% 機率使敵人受到穿刺`],
  [/^(\d+(?:\.\d+)?)% increased Totem Placement speed$/i, (value) => `增加 ${value}% 圖騰放置速度`],
  [/^Attacks used by Totems have (\d+(?:\.\d+)?)% increased Attack Speed$/i, (value) => `圖騰使用的攻擊有 ${value}% 增加攻擊速度`],
  [/^Gain (\d+) Rage on Melee Hit$/i, (value) => `近戰擊中時獲得 ${value} 點盛怒`],
  [/^\+(\d+) to Maximum Power Charges$/i, (value) => `+${value} 最大暴擊球數量`],
  [/^\+(\d+) to Maximum Frenzy Charges$/i, (value) => `+${value} 最大狂怒球數量`],
  [/^\+(\d+) to Maximum Endurance Charges$/i, (value) => `+${value} 最大耐力球數量`]
];

const genericNodeTermTranslations: Array<[string, string]> = [
  ['Attack and Cast Speed', '攻擊和施放速度'],
  ['Critical Strike Chance', '暴擊率'],
  ['Spell Critical Strike Chance', '法術暴擊率'],
  ['Damage Over Time Mastery', '持續傷害專精'],
  ['Reservation Efficiency', '保留效用'],
  ['Reservation Efficiency of Heralds', '捷的保留效用'],
  ['Retaliation Skill', '復仇技能'],
  ['Guard Skill', '防衛技能'],
  ['Movement Skill', '位移技能'],
  ['Brand Recall', '烙印呼喚'],
  ['with Shield', '持盾時'],
  ['while Fortified', '護體時'],
  ['Aura Effect', '光環效果'],
  ['Aura Area of Effect', '光環範圍效果'],
  ['Cooldown Recovery Rate', '冷卻恢復率'],
  ['Mana Regeneration', '魔力回復'],
  ['Life Leeched per Second', '每秒生命偷取'],
  ['Reduced Enemy Stun Threshold', '降低敵人暈眩門檻'],
  ['Life Regeneration', '生命回復'],
  ['Energy Shield', '能量護盾'],
  ['Energy Shield Recharge Rate', '能量護盾充能率'],
  ['Physical Damage Reduction', '物理傷害減免'],
  ['Spell Suppression', '法術壓抑'],
  ['Area of Effect', '範圍效果'],
  ['Area Of Effect', '範圍效果'],
  ['Area Damage', '範圍傷害'],
  ['Attack Damage', '攻擊傷害'],
  ['Attack Speed', '攻擊速度'],
  ['Cast Speed', '施放速度'],
  ['Curse Cast Speed', '詛咒施放速度'],
  ['Curse Duration', '詛咒持續時間'],
  ['Spell Damage', '法術傷害'],
  ['Spell Block', '法術傷害格擋率'],
  ['Spell Area of Effect', '法術範圍效果'],
  ['Spell Damage Over Time Multiplier', '法術持續傷害加成'],
  ['Spell Damage Over Time', '法術持續傷害'],
  ['Projectile Damage', '投射物傷害'],
  ['Projectile Speed', '投射物速度'],
  ['Minion Damage', '召喚物傷害'],
  ['Minion Life', '召喚物生命'],
  ['Skill Duration', '技能持續時間'],
  ['Life Recoup', '生命補償'],
  ['Life Gain on Hit', '擊中獲得生命'],
  ['Life Leech Speed', '生命偷取速度'],
  ['Life Flask Recovery', '生命藥劑回復'],
  ['Energy Shield Leech', '能量護盾偷取'],
  ['Elemental Resistances', '元素抗性'],
  ['Chaos Resistance', '混沌抗性'],
  ['Elemental Ailment Avoidance', '元素異常狀態避免'],
  ['Elemental Ailment Duration', '元素異常狀態持續時間'],
  ['Status Ailment Chance', '異常狀態機率'],
  ['Fire Resistance', '火焰抗性'],
  ['Cold Resistance', '冰冷抗性'],
  ['Lightning Resistance', '閃電抗性'],
  ['Cold Damage Over Time Multiplier', '冰冷持續傷害加成'],
  ['Physical Damage Over Time Multiplier', '物理持續傷害加成'],
  ['Poison Damage Multiplier', '中毒傷害加成'],
  ['Bleed Damage Multiplier', '流血傷害加成'],
  ['Physical Damage', '物理傷害'],
  ['Elemental Damage', '元素傷害'],
  ['Chaos Damage', '混沌傷害'],
  ['Burning Damage', '燃燒傷害'],
  ['Stun Duration', '暈眩持續時間'],
  ['Stun Threshold Reduction', '敵人暈眩門檻降低'],
  ['Stun Threshold', '暈眩門檻'],
  ['Stun Recovery', '暈眩恢復'],
  ['Stun Avoidance', '避免暈眩'],
  ['Stun', '暈眩'],
  ['Lightning Damage', '閃電傷害'],
  ['Cold Damage', '冰冷傷害'],
  ['Fire Damage', '火焰傷害'],
  ['Critical Strike', '暴擊'],
  ['Multiplier', '加成'],
  ['Effect', '效果'],
  ['Duration', '持續時間'],
  ['Placement Speed', '放置速度'],
  ['Ignite Chance', '點燃機率'],
  ['Freeze Chance', '冰凍機率'],
  ['Shock Chance', '感電機率'],
  ['Impale Chance', '穿刺機率'],
  ['Impale Effect', '穿刺效果'],
  ['Onslaught Effect', '猛攻效果'],
  ['Fortify on Melee Stun', '近戰暈眩時獲得護體'],
  ['Avoid Interruption while Casting', '施放時避免被中斷'],
  ['Chance to Poison with Spells', '法術中毒機率'],
  ['Withered Expiry Rate', '凋零消逝速度'],
  ['Fortification Gain', '護體獲得量'],
  ['Flask Charges against Marked Enemy', '對印記敵人的藥劑充能'],
  ['Damage against Marked Enemy', '對印記敵人的傷害'],
  ['Banner Maximum Valour', '鬥旗最大英勇值'],
  ['Banner Area of Effect', '鬥旗範圍效果'],
  ['Banner Aura Effect', '鬥旗光環效果'],
  ['Link Mana Cost', '連結魔力消耗'],
  ['Poison Chance', '中毒機率'],
  ['Bleed Chance', '流血機率'],
  ['Bleed Duration', '流血持續時間'],
  ['Bleeding', '流血'],
  ['Faster Bleeding', '流血加速'],
  ['Faster Ailments', '異常狀態加速'],
  ['Exerted', '竭盡'],
  ['Onslaught', '猛攻'],
  ['Blind', '致盲'],
  ['Ignite', '點燃'],
  ['Movement', '移動'],
  ['Flasks', '藥劑'],
  ['Offering', '奉獻'],
  ['Spectres', '幽魂'],
  ['Recovery Rate', '恢復率'],
  ['Recovery rate', '恢復率'],
  ['per Second', '每秒'],
  ['Forking Angle', '分叉角度'],
  ['Corpse', '屍體'],
  ['Shrine', '神龕'],
  ['Golem', '魔像'],
  ['Curse', '詛咒'],
  ['Aura', '光環'],
  ['Skill', '技能'],
  ['Speed', '速度'],
  ['Cooldown', '冷卻'],
  ['Reduced', '減少'],
  ['Increased', '增加'],
  ['Leech', '偷取'],
  ['Recoup', '補償'],
  ['Recharge Rate', '充能率'],
  ['Gain', '獲得量'],
  ['Chance', '機率'],
  ['Overwhelm', '壓倒'],
  ['Valour', '英勇值'],
  ['Fortification', '護體'],
  ['Arcane Surge Effect', '秘能波動效果'],
  ['Arcane Surge', '秘能波動'],
  ['Maximum', '最大'],
  ['Armour', '護甲'],
  ['Evasion', '閃避'],
  ['Accuracy', '命中'],
  ['Block', '格擋'],
  ['Block Chance', '格擋率'],
  ['Mana', '魔力'],
  ['Life', '生命'],
  ['Strength', '力量'],
  ['Dexterity', '敏捷'],
  ['Intelligence', '智慧'],
  ['Attack', '攻擊'],
  ['Charge', '充能'],
  ['Frenzy Charge', '狂怒球'],
  ['Endurance Charge', '耐力球'],
  ['Power Charge', '暴擊球'],
  ['Brand', '烙印'],
  ['Mine', '地雷'],
  ['Heralds', '捷'],
  ['Herald', '捷'],
  ['Charm', '咒符'],
  ['Minion', '召喚物'],
  ['Axe', '斧'],
  ['Bow', '弓'],
  ['Claw', '爪'],
  ['Dagger', '匕首'],
  ['Sword', '劍'],
  ['Mace', '錘'],
  ['Sceptre', '權杖'],
  ['Wand', '法杖'],
  ['Staff', '長杖'],
  ['Shield', '盾牌'],
  ['Totem', '圖騰'],
  ['Trap', '陷阱'],
  ['Mark', '印記'],
  ['Poison', '中毒'],
  ['Hex', '咒術'],
  ['Link', '連結'],
  ['Retaliation', '復仇'],
  ['Warcry', '戰吼'],
  ['Flask', '藥劑'],
  ['Life Flasks', '生命藥劑'],
  ['Mana Flasks', '魔力藥劑'],
  ['Tincture', '萃取物'],
  ['Rage', '盛怒'],
  ['Chaos', '混沌'],
  ['Lightning', '閃電'],
  ['Cold', '冰冷'],
  ['Fire', '火焰'],
  ['Physical', '物理'],
  ['Elemental', '元素'],
  ['Projectile', '投射物'],
  ['Melee', '近戰'],
  ['Damage', '傷害'],
  ['Damage Over Time', '持續傷害'],
  ['Ailment Effect', '異常狀態效果'],
  ['Ailment Avoidance', '異常狀態避免'],
  ['Ailment Duration', '異常狀態持續時間'],
  ['Penetration', '穿透'],
  ['Recovery', '恢復'],
  ['Recovery Rate', '恢復率'],
  ['Charges Gained', '充能獲得量'],
  ['Life on Kill', '擊殺時獲得生命'],
  ['Energy Shield on Kill', '擊殺時獲得能量護盾'],
  ['Rage on Hit', '擊中獲得盛怒'],
  ['Buff Effect', '增益效果'],
  ['Mirage Archer', '幻影射手'],
  ['Ignore', '無視'],
  ['Phasing', '迷蹤'],
  ['Consumed a Corpse', '消耗屍體'],
  ['against Marked Enemy', '對印記敵人'],
  ['against Marked Enemies', '對印記敵人'],
  ['Marked Enemy', '印記敵人'],
  ['Detonation Speed', '引爆速度'],
  ['Trigger Area', '觸發範圍'],
  ['Throwing Speed', '投擲速度'],
  ['Usable Duration', '可使用持續時間'],
  ['On Kill', '擊殺時'],
  ['on Kill', '擊殺時'],
  ['on Hit', '擊中時'],
  ['Strike Range', '打擊距離'],
  ['Mana Cost', '魔力消耗'],
  ['Reduced Mana Cost', '減少魔力消耗'],
  ['Reduced Cost', '減少消耗'],
  ['Flask Charges Gained', '藥劑充能獲得量'],
  ['Flask Effect', '藥劑效果'],
  ['One Handed', '單手'],
  ['Dual Wielding', '雙持'],
  ['Dual Wield', '雙持'],
  ['Two Hand', '雙手'],
  ['Two Handed Melee', '雙手近戰'],
  ['Cooldown Recovery', '冷卻恢復率'],
  ['Life Flask', '生命藥劑'],
  ['Mana Flask', '魔力藥劑'],
  ['Weapon', '武器'],
  ['Defences', '防禦'],
  ['Mastery', '專精'],
  ['Socket', '珠寶插槽'],
  ['found', '發現'],
  ['Wisps', '微光']
];

const sortedGenericNodeTermTranslations = [...genericNodeTermTranslations].sort((a, b) => b[0].length - a[0].length);

const genericNodeConnectorTranslations: Array<[string, string]> = [
  [' and ', '和'],
  [', ', '、']
];

const sortedGenericNodeConnectorTranslations = [...genericNodeConnectorTranslations].sort((a, b) => b[0].length - a[0].length);

const tryTranslateGenericNodeName = (name: string): string | undefined => {
  let output = name;

  sortedGenericNodeTermTranslations.forEach(([source, target]) => {
    output = output.replaceAll(source, target);
  });

  sortedGenericNodeConnectorTranslations.forEach(([source, target]) => {
    output = output.replaceAll(source, target);
  });

  return /[A-Za-z]/.test(output) ? undefined : output;
};

export const translateSkillTreeNodeName = (name: string | undefined): string => {
  if (!name) {
    return '';
  }

  const normalizedName = name.trim();

  if (nodeNameTranslations[normalizedName]) {
    return nodeNameTranslations[normalizedName];
  }

  if (normalizedName.endsWith(' Mastery')) {
    const base = normalizedName.slice(0, -' Mastery'.length);
    return `${translateSkillTreeNodeName(base)}專精`;
  }

  const generic = tryTranslateGenericNodeName(normalizedName);
  if (generic) {
    return generic;
  }

  return normalizedName;
};

export const translateSkillTreeStatText = (text: string): string => {
  for (const [pattern, formatter] of regexTransforms) {
    const match = text.match(pattern);
    if (match) {
      const translated = formatter(...match.slice(1));
      if (!/[A-Za-z]/.test(translated)) {
        return translated;
      }
    }
  }

  const translated = replaceTerms(text);
  return /[A-Za-z]/.test(translated) ? text : translated;
};
